.travis.yml
CHANGELOG.md
README.rst
docs/source/conf.py
docs/source/quickstart.rst
riscv_config/__init__.py

- typos in quickstart doc
- disabled deployment to repository until authentication issue is fixed.

Doc updates

---

CHANGELOG.md
riscv_config/__init__.py
riscv_config/schemaValidator.py
riscv_config/schemas/schema_isa.yaml

- Removed legal_checks function.
- Closes #22

Bug fix #22

---

.travis.yml
CHANGELOG.md
docs/source/yaml-specs.rst
examples/rv32i_isa.yaml
examples/rv64i_isa.yaml
riscv_config/__init__.py
riscv_config/checker.py
riscv_config/schemaValidator.py
riscv_config/schemas/schema_isa.yaml

- Changed implemented in rv32 and rv64 nodes to accessible.
- Modified appropriate definitions for fields dependent on specific extensions like NSU.
- Closes #14

Csr tests and accessiblity changes

---

CHANGELOG.md
docs/source/quickstart.rst
riscv_config/__init__.py
riscv_config/checker.py

- Changed quickstart 'riscv_config' to 'riscv-config'
- Changed checker.py to add  check_reset_fill_fields() description

Document changes

---

CHANGELOG.md
riscv_config/__init__.py
riscv_config/schemas/schema_isa.yaml

- default mpp value to 0
- adding defaults to sub-fields of mtvec

fixed defaults

---

CHANGELOG.md
riscv_config/__init__.py
riscv_config/checker.py
riscv_config/schemas/schema_isa.yaml

Fixed the relationship between fflags, frm and fcsr
Enable subfield to be shadow field of whole csr, and vice versa

Fixed the relationship between fflags, frm and fcsr

---

.gitignore
CHANGELOG.md
riscv_config/__init__.py
riscv_config/schemaValidator.py
riscv_config/schemas/schema_isa.yaml
riscv_config/warl.py

- add support for detection of svnapot in ISA string
- genralize conversion of hex, oct, bin values to int in warl functions
- machine flat schema to include wlrl types as well

clean up warl and svnapot support added

---

CHANGELOG.md
docs/source/yaml-specs.rst
riscv_config/__init__.py
setup.cfg

- Added setup.cfg to automate bumpversion
- Fix wording for legal strings in dependency warl fields.

Documentation Fix.

---

CHANGELOG.md
riscv_config/__init__.py
riscv_config/warl.py
setup.cfg

fix for index-based dependency checks in warl string.

fix for warl dependency checks

---

CHANGELOG.md
riscv_config/__init__.py
riscv_config/warl.py
setup.cfg

if the value being tested is out of bounds, then skip with error immediately

out of bound check for warl islegal function

---

.github/workflows/main.yml
CHANGELOG.md
docs/source/new-extensions.rst
riscv_config/__init__.py
setup.cfg

- documentation cleanup for adding new extensions in riscv-config
- disabled pdf asset generation for each release.

documentation clean up

---

CHANGELOG.md
examples/rv64i_debug.yaml
riscv_config/__init__.py
riscv_config/checker.py
riscv_config/errors.py
riscv_config/schemas/schema_debug.yaml
riscv_config/schemas/schema_isa.yaml
riscv_config/warl.py
setup.cfg

- Add support for indexed registers
- Add schemas for triggers
- Fix bugs in WARL class
- Add function to get a legal value from WARL fields.

Add Indexed reg support

---

CHANGELOG.md
riscv_config/__init__.py
riscv_config/checker.py
riscv_config/constants.py
riscv_config/isa_validator.py
riscv_config/schemaValidator.py
riscv_config/schemas/schema_isa.yaml

Added ISA and associated legality checks.
Added CSR (vxsat) to schema (credits: chuanhua)

Adding sub-extensions of P-SIMD

---

CHANGELOG.md
examples/rv32i_isa.yaml
examples/rv32i_isa_checked.yaml
riscv_config/__init__.py
riscv_config/schemaValidator.py
riscv_config/schemas/schema_isa.yaml
setup.cfg

special checks for vxsat csr added which apply only the max-xlen subsections of the csr

 special checks for vxsat

---

CHANGELOG.md
riscv_config/__init__.py
riscv_config/constants.py
riscv_config/isa_validator.py
setup.cfg

I would like to add V support to riscv-config, this is the first PR.

check V extensions ISA string constraints

---

CHANGELOG.md
riscv_config/__init__.py
riscv_config/constants.py
setup.cfg

See https://github.com/riscv/riscv-zicond/releases/download/v1.0-draft-20230120/riscv-zicond_1.0-draft-20230120.pdf

Support for Zicond extension

---

.github/workflows/main.yml
.github/workflows/test.yml
CHANGELOG.md
requirements.txt
riscv_config/__init__.py
riscv_config/checker.py
riscv_config/constants.py
riscv_config/isa_validator.py
riscv_config/schemaValidator.py
riscv_config/schemas/schema_isa.yaml
setup.cfg
setup.py

- Add support for Srnmi extension
- All extension existence checks to be performed on extension\_list from isa validator.

smrnmi support

---

CHANGELOG.md
riscv_config/__init__.py
riscv_config/checker.py
riscv_config/schemaValidator.py
riscv_config/schemas/schema_isa.yaml
setup.cfg

- Fix Checks for FCSR, FFLAGS and FRM to depend on F instead of U.

Patch fcsr checks

---

CHANGELOG.md
riscv_config/__init__.py
riscv_config/constants.py
riscv_config/isa_validator.py
setup.cfg

See https://github.com/riscv/riscv-isa-manual/releases/tag/draft-20230131-c0b298a
Required for https://github.com/riscv-non-isa/riscv-arch-test/pull/330

Support for Zfa extension

---

CHANGELOG.md
riscv_config/__init__.py
riscv_config/constants.py
setup.cfg

Adds support for unratified Zacas extension.
The specification is here: https://github.com/riscv/riscv-zacas

Add support for unratified Zacas

---

CHANGELOG.md
riscv_config/__init__.py
riscv_config/constants.py
riscv_config/schemas/schema_isa.yaml

Add hade/stce/pbmte bits to menvcfg
Add menvcfgh with hade/stce/pbmte bits.

Add support Svadu extension

---

.github/pull_request_template.md
CHANGELOG.md
CONTRIBUTING.rst
docs/source/CONTRIBUTING.rst
docs/source/index.rst
docs/source/quickstart.rst
docs/source/yaml-specs.rst
riscv_config/__init__.py
riscv_config/checker.py
riscv_config/isa_validator.py
riscv_config/schemas/schema_isa.yaml
riscv_config/schemas/schema_platform.yaml
setup.cfg

- Closes issue #110
- Closes issue #108
- Closes issue #114
- Closes issue #127
- Closes issue #82
- Closes issue #103
- updated contribution guidelines on versioning
- added docs for indexed

Bump 3.12.0

---

CHANGELOG.md
riscv_config/__init__.py
riscv_config/constants.py
setup.cfg

> Provide a detailed description of the changes performed by the PR.
Add Zabha extension
> Please list all the issues related to this PR. Use NA if no issues exist.
- [X ] Unratified
> List the extensions that your PR affects. In case of unratified extensions, please provide a link to the spec draft that was referred to make this PR.
https://github.com/riscv/riscv-zabha
- [X ] Make sure you have updated the versions in `setup.cfg` and `riscv_config/__init__.py`. Refer to CONTRIBUTING.rst file for further information.
- [ X] Make sure to have created a suitable entry in the CHANGELOG.md.

Add Zabha extension
