CHANGELOG.md, riscv_config/checker.py, riscv_config/schemas/schema_platform.yaml
- doc issue for mtimecmp
- mimpid is now part of the default setters list
Close #26
=> Issue 29 bug fixes

CHANGELOG.md, docs/source/quickstart.rst, riscv_config/__init__.py, setup.py
- Changed minimum python version requirement to 3.6.0 which is typically easy to install on all
major distributions
- Updated readme with better installation instructions
=> Switch to python-3.6.0 as minimum requirement

CHANGELOG.md, docs/source/yaml-specs.rst, examples/rv32i_isa.yaml, examples/rv64i_isa.yaml, riscv_config/__init__.py, riscv_config/schemaValidator.py, riscv_config/schemas/schema_isa.yaml
- msb,lsb values of "SD" field in mstatus must be 63 in rv64 mode
- added checks for reset value of misa to adhere to the extensions enabled in the input yaml
- fixed dead-link in the docs.
=> bump to 2.6.1

CHANGELOG.md, riscv_config/__init__.py, riscv_config/schemas/schema_isa.yaml
The value is already checked in `schemaValidator.py` but not allowed by
the schema.
=> Allow B extension for ISA string

CHANGELOG.md, examples/rv32i_custom.yaml, examples/rv32i_platform.yaml, examples/rv64i_isa.yaml, riscv_config/__init__.py, riscv_config/checker.py, riscv_config/schemaValidator.py, riscv_config/schemas/schema_debug.yaml, riscv_config/schemas/schema_isa.yaml, riscv_config/schemas/schema_platform.yaml
- fixed issue #58 by adding extra checks for bitmask
- fixed issue #59 by removing custom cause from platform yaml
- resolved inconsistencies in the use of "xlen" and "supported_xlen" in schemaValidator
- added extra "shadow_type" fields in the csr schemas. These indicate the nature of shadow
(read-only, read-write, etc).
- added parking_loop node in debug_schema to indicate the address of debug rom. Can be empty in
implementations which do not have this feature
=> Debug and shadow fixes

CHANGELOG.md, riscv_config/__init__.py, riscv_config/schemas/schema_isa.yaml
When I wrote a python script to parse the yaml generated by riscv-config, I found All other hpmcounter* have shadow_type field except for hpmcounter17 .
=> add the missing shadow_type field for hpmcounter17 

CHANGELOG.md, riscv_config/__init__.py, riscv_config/checker.py, riscv_config/schemas/schema_isa.yaml
- added mbe and sbe fields in mstatush
- fixed default setter for vsstatus in RV32 mode
=> bump to 2.12.1

CHANGELOG.md, riscv_config/__init__.py, riscv_config/schemaValidator.py, riscv_config/schemas/schema_isa.yaml, riscv_config/schemas/schema_platform.yaml, setup.cfg
This patch add support for cmo extensions with related part of Xenvcfg CSRs.
=> add support for zicbo* extensions

.github/workflows/test.yml, CHANGELOG.md, docs/source/code-doc.rst, docs/source/yaml-specs.rst, examples/rv32i_isa_checked.yaml, examples/rv64i_isa.yaml, examples/rv64i_isa_checked.yaml, riscv_config/__init__.py, riscv_config/checker.py, riscv_config/errors.py, riscv_config/schemaValidator.py, riscv_config/schemas/schema_debug.yaml, riscv_config/schemas/schema_isa.yaml, riscv_config/warl.py, setup.cfg
- created new warl class for warl node handling
- better comments
- more functions to keep things simple
- fixed a lot of bugs in checking legal values
- bitmask and range values can now co-exist in a legal string
- added new and improved checks for syntax validity of warl strings
- fixed validationError function to correctly print all errors (dict and/or list)
- removed wr\_illegal checks from the schema since they are now done as part of the new warl class
checks
- updates to the new warl checks and reset-value checks
- satp.mode should have one of sv\* translation schemes as a legal value. (#89)
- default setters for pmps fixed
- pmp checks have been improved (close #88)
- improve WARL documentation
=> warl improvement and other changes (bump to 3.0.0)

CHANGELOG.md, riscv_config/__init__.py, riscv_config/checker.py, setup.cfg
- Check if YAMLs are None before they're merged for performing CSR checks.
- Perform XLEN specific satp checks based on XLEN value.
- Check triggers only when debug CSRs are available.
=> minor fixes in checker

CHANGELOG.md, riscv_config/__init__.py, riscv_config/constants.py, riscv_config/schemas/schema_isa.yaml, setup.cfg
This PR updates the Z_extensions list with the ISA strings required by the Code size reduction extension.
=> Add support for Code Size Reduction Extension

CHANGELOG.md, riscv_config/__init__.py, riscv_config/checker.py, setup.cfg
This PR changes the supervisor checks. ``satp.mode`` checks will now only happen if the CSR is accessible.
Resolves issue #144
S - Supervisor
=> Fix satp checks

CHANGELOG.md, riscv_config/__init__.py, riscv_config/warl.py, setup.cfg
#126 introduced support for uarch-dependencies - however, the subfield variable in warl_class was assigned to None instead of `''`. This caused a few default checks to fail - leading to false negatives.
This PR fixes that issue by re-assigning subfield to `''` and modifying the checks accordingly.
None
None
=>  do not assign subfield to None

.github/workflows/main.yml, CHANGELOG.md, riscv_config/__init__.py, riscv_config/constants.py, setup.cfg
- Include Sdext in the list of S extensions.
- NA
- Sdext
=> include Sdext in the list of S extensions

CHANGELOG.md, riscv_config/__init__.py, riscv_config/isa_validator.py, setup.cfg
This PR adds a function that returns the values for `march` and `mabi` arguments for gcc for a given ISA string. 
N/A
N/A
=> Added function that returns the march and mabi for gcc from a given ISA

CHANGELOG.md, riscv_config/__init__.py, riscv_config/checker.py, riscv_config/warl.py, setup.cfg
- use the "hartX" naming for the merged dict
- improve logging statements
- update the "fields" node of each csr in the normalized custom yaml
NA
Affects custom CSR checks only.
=> Custom csr fields fix

CHANGELOG.md, riscv_config/__init__.py, riscv_config/isa_validator.py, setup.cfg
This PR adds an option to generate march strings without custom extensions.
#161 
All custom extensions (X***) will be affected.
=> Support march generation without custom extensions

CHANGELOG.md, riscv_config/__init__.py, riscv_config/constants.py, setup.cfg
> Add Ssdbltrp, Smdbltrp, Sddbltrp extensions
> N/A
> https://github.com/riscv/riscv-double-trap
=> Add ssdbltrp, smdbltrp, sddbltrp

CHANGELOG.md, riscv_config/__init__.py, riscv_config/checker.py, setup.cfg
> There is a yaml_dump argument provided to the function that directly dump the normalized yaml, but with the yaml_dump_flag the function returns the yaml object instead.
> NA
> NA
=> Added yaml dump flag

CHANGELOG.md, riscv_config/__init__.py, riscv_config/isa_validator.py, riscv_config/utils.py, setup.cfg
1. Svnapot will be excluded from the list of extensions used for march generation.
2. load_yaml will log raw error messages from ruamel.
#178 and #179
1. Svnapot - Standard Extension for NAPOT Translation Contiguity
=> exclude svnapot and fix errors logged from ruamel.
